Pandas হলো পাইথনের সবচেয়ে জনপ্রিয় এবং শক্তিশালী **Data Analysis** এবং **Manipulation** লাইব্রেরি। এটি মূলত টেবিল বা স্ট্রাকচারড ডাটা নিয়ে কাজ করার জন্য তৈরি।

### Pandas কী?

Pandas একটি ওপেন সোর্স লাইব্রেরি যা **Series** (একমাত্রিক) এবং **DataFrame** (দ্বিমাত্রিক বা টেবিল) এর মাধ্যমে ডাটা হ্যান্ডেল করে। আপনি একে পাইথনের "Excel" বা "SQL" বলতে পারেন।

### কেন এটি ব্যবহার করা হয়?

* **Ease of Use:** খুব কম কোড লিখে জটিল ডাটা ক্যালকুলেশন করা যায়।
* **Speed:** এটি অভ্যন্তরীণভাবে NumPy ব্যবহার করে, তাই বড় ডাটাবেস নিয়ে কাজ করতে এটি অত্যন্ত দ্রুত।
* **Handling Messy Data:** অগোছালো বা মিসিং ডাটা (Missing Data) ক্লিন করার জন্য এটি সেরা টুল।

### Pandas দিয়ে যা যা করা যায়:

1. **Data Loading:** CSV, Excel, SQL, বা JSON ফাইল থেকে সরাসরি ডাটা লোড করা।
2. **Data Cleaning:** ডুপ্লিকেট ভ্যালু বাদ দেওয়া এবং ফাকা ঘর (NaN) পূরণ করা।
3. **Filtering & Sorting:** নির্দিষ্ট শর্ত অনুযায়ী ডাটা খুঁজে বের করা বা সাজানো।
4. **Aggregation:** ডাটার গড় (Mean), যোগফল (Sum), বা গ্রুপ করে (GroupBy) বিশ্লেষণ করা।
5. **Merging:** একাধিক টেবিল বা ডাটাসেটকে একত্রে জোড়া লাগানো।

---

In [1]:
import pandas as pd
import numpy as np
from pyarrow import dictionary
from xxlimited_35 import Null

pd.__version__

'3.0.0'

# Different File Loading in Pandas
Pandas প্রায় সব ধরনের জনপ্রিয় ডাটা ফরম্যাট লোড বা রিড করতে সক্ষম। নিচে এর একটি সংক্ষিপ্ত তালিকা এবং বহুল ব্যবহৃত ফরম্যাট সম্পর্কে তথ্য দেওয়া হলো:

### ১. Pandas যেসব ফরম্যাট সাপোর্ট করে:

Pandas-এ ডাটা রিড করার জন্য মূলত `read_` প্রিফিক্স দিয়ে ফাংশনগুলো ব্যবহার করা হয়:

* **Text/Flat Files:** CSV, TSV, Fixed-width (fwf)
* **Spreadsheets:** Excel (.xlsx, .xls)
* **Structured Data:** JSON, XML, HTML
* **Binary/Big Data:** Parquet, HDF5, Feather, Pickle
* **Databases:** SQL (MySQL, PostgreSQL, SQLite) থেকে সরাসরি ক্যুয়েরি করে ডাটা আনা যায়।
* **Clipboard:** কপি করা ডাটা সরাসরি `read_clipboard()` দিয়ে আনা সম্ভব।


### ২. AI-ML ও Data Science-এ সবচেয়ে জনপ্রিয় ফরম্যাট:

সবচেয়ে বেশি ব্যবহৃত ফরম্যাট হলো **CSV (Comma Separated Values)**।

**কেন CSV সবচেয়ে বেশি ব্যবহৃত হয়?**

* **Universal Compatibility:** এটি যেকোনো ল্যাঙ্গুয়েজ বা টুলের সাথে চলে।
* **Human Readable:** এটি টেক্সট এডিটরে সহজেই পড়া যায়।
* **Simplicity:** কোনো জটিল মেটাডাটা বা এনক্রিপশন থাকে না, তাই ডাটা ট্রান্সফার সহজ।

> **বিঃদ্রঃ** বড় ডাটাসেট বা বিগ ডাটার (Big Data) ক্ষেত্রে বর্তমানে **Parquet** ফরম্যাট অনেক জনপ্রিয় হচ্ছে, কারণ এটি কম্প্রেসড থাকে এবং মেমোরি অনেক কম খরচ করে।

In [2]:
# Loading a CSV file

df = pd.read_csv("student_data.csv")        # It will read the csv file
df.head()                                   # It will show the first 5 rows of the dataset
# print(df.head())
# df.info()                                   # It will show the information of the dataset
# df.describe()                               # It will show the statistical information of the dataset
# print(df)                                   # It will print the whole dataset
# print(type(df))                             # It will print the data type of the dataset, and it's <class 'pandas.DataFrame'>
# print(df.shape)
# print(df.columns)
# print(df.index)
# print(df.dtypes)
# print(df.size)
# print(df.memory_usage())

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [3]:
# Finding all data from a column

student_id_column = df['StudentID']
print(student_id_column)
print(type(student_id_column))              # <class 'pandas.Series'> means student_id_column is a panda's series

0     PH1001
1     PH1002
2     PH1003
3     PH1004
4     PH1005
5     PH1006
6     PH1007
7     PH1008
8     PH1009
9     PH1010
10    PH1011
11    PH1012
12    PH1013
13    PH1014
14    PH1015
15    PH1016
16    PH1017
17    PH1018
18    PH1019
19    PH1020
Name: StudentID, dtype: str
<class 'pandas.Series'>

In [4]:
# Loading an Excel file

df_excel = pd.read_excel("phitron_student_marks.xlsx")
df_excel.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [5]:
# print(df_json.head())
print(type(df_excel))
print(df_excel.dtypes)
# print(df_excel.shape)
# print(df_excel.columns)
# print(df_excel.index)
# print(df_excel.memory_usage())
# print(df_excel.info())
# print(df_excel.describe())
# print(df_excel.head(10))
# print(df_excel.tail(10))
# print(df_excel.isnull().sum())

<class 'pandas.DataFrame'>
StudentID                   str
FullName                    str
Data Structure Marks    float64
Algorithm Marks         float64
Python Marks            float64
CompletionStatus            str
EnrollmentDate              str
Instructor                  str
Location                    str
dtype: object

In [6]:
# Loading a Parquet file

df_parquet = pd.read_parquet("students.parquet")
df_parquet.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [7]:
# print(df_parquet.head())
print(type(df_parquet))
print(df_parquet.dtypes)
# print(df_parquet.shape)
# print(df_parquet.columns)
# print(df_parquet.index)
# print(df_parquet.memory_usage())
# print(df_parquet.info())
# print(df_parquet.describe())
# print(df_parquet.head(10))
# print(df_parquet.tail(10))
# print(df_parquet.isnull().sum())

<class 'pandas.DataFrame'>
StudentID                   str
FullName                    str
Data Structure Marks    float64
Algorithm Marks         float64
Python Marks            float64
CompletionStatus            str
EnrollmentDate              str
Instructor                  str
Location                    str
dtype: object

In [8]:
# Loading a JSON file

df_json = pd.read_json("data.json")
df_json.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks
0,PH1001,Alif Rahman,85,85,88
1,PH1002,Fatima Akhter,92,92,90
2,PH1004,Jannatul Ferdous,78,78,82

In [9]:
# print(df_json.head())
print(type(df_json))
print(df_json.dtypes)
# print(df_json.shape)
# print(df_json.columns)
# print(df_json.index)
# print(df_json.memory_usage())
# print(df_json.info())
# print(df_json.describe())
# print(df_json.head(10))
# print(df_json.tail(10))
# print(df_json.isnull().sum())

<class 'pandas.DataFrame'>
StudentID                 str
FullName                  str
Data Structure Marks    int64
Algorithm Marks         int64
Python Marks            int64
dtype: object

In [10]:
# Show the whole dataframe dataset
df_excel

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [11]:
# Show some data from the top of the dataframe

df_excel.head()
# df_excel.head(5)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [12]:
# Show some data from the bottom of the dataframe

df_excel.tail()
# df_excel.tail(5)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [13]:
# Show the columns of the dataframe

df_excel.columns        # This column is not a function to call with (). It's just an attribute of the Dataframe class.

Index(['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks',
       'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor',
       'Location'],
      dtype='str')

In [14]:
# Save the columns in a list

# column_list = df_excel.columns.to_list()
# column_list = list(df_excel.columns)
column_list = np.array(df_excel.columns)
print(column_list)
print(column_list.dtype)

['StudentID' 'FullName' 'Data Structure Marks' 'Algorithm Marks'
 'Python Marks' 'CompletionStatus' 'EnrollmentDate' 'Instructor'
 'Location']
object

In [15]:
# Show the full index information of the Dataframe

df_excel.index
index_list = np.array(df_excel.index)
print(index_list)
print(index_list.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
int64

In [16]:
# Show full information about the Dataframe

df_excel.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     str
 1   FullName              20 non-null     str
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     str
 6   EnrollmentDate        20 non-null     str
 7   Instructor            20 non-null     str
 8   Location              20 non-null     str
dtypes: float64(3), str(6)
memory usage: 2.6 KB

In [17]:
# Show a specific number of random sample data from the Dataframe

df_excel.sample(5)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet

In [18]:
# Show statistical values of the Dataframe

df_excel.describe()

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

# Transforming to dataframe from inbuilt datas

In [19]:
# Converting a simple python list into a dataframe

list_01 = [['Alice', 25], ['Bob', 30], ['Charlie', 28]]

# list_01_df = pd.DataFrame(list_01)
list_01_df = pd.DataFrame(list_01, columns=['Name', 'Age'])
# list_01_df = pd.DataFrame(list_01, columns=['Name', 'Age'], index=[1, 2, 3])
list_01_df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   28

In [20]:
print(type(list_01_df))
print(list_01_df.dtypes)

<class 'pandas.DataFrame'>
Name      str
Age     int64
dtype: object

In [21]:
# Converting a simple python tuple into a dataframe

tuple_01 = (('Alice', 25), ('Bob', 30), ('Charlie', 28))

# tuple_01_df = pd.DataFrame(tuple_01)
tuple_01_df = pd.DataFrame(tuple_01, columns=['Name', 'Age'])
# tuple_01_df = pd.DataFrame(tuple_01, columns=['Name', 'Age'], index=[1, 2, 3])
tuple_01_df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   28

In [22]:
# Converting a simple python dictionary into a dataframe

dictionary_01 = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 29, 28]
}
dictionary_01_df = pd.DataFrame(dictionary_01)
# dictionary_01_df = pd.DataFrame(dictionary_01, index=[1, 2, 3])   # Column names are automatically assigned from the dictionary keys
dictionary_01_df

      Name  Age
0    Alice   25
1      Bob   29
2  Charlie   28

In [23]:
# Converting a list of dictionaries into a dataframe

list_02 = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'Paris'},
    {'Name': 'Charlie', 'Age': 28}
]
list_02_df = pd.DataFrame(list_02)
list_02_df

# See carefully; in the last dictionary of the list, there is no City, therefore, it's considered as a Null or NaN.

      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   28       NaN

# Accessing values from Dataframe

In [24]:
# Accessing a column of a dataframe

df_excel['FullName']

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
Name: FullName, dtype: str

In [25]:
type(df_excel['FullName'])

pandas.Series

# Accessing a row of a dataframe

Pandas-এ একটি **DataFrame** থেকে নির্দিষ্ট রো (Row) অ্যাক্সেস করার জন্য প্রধানত দুটি পদ্ধতি ব্যবহার করা হয়। নিচে তা সংক্ষেপে আলোচনা করা হলো:

### ১. `.iloc[]` (Integer-based Indexing)

যখন আপনি ইনডেক্সের **পজিশন বা সংখ্যা** (যেমন: ০, ১, ২...) ব্যবহার করে রো অ্যাক্সেস করতে চান, তখন `iloc` ব্যবহার করা হয়।

* **ব্যবহার:** `df.iloc[index_number]`
* **উদাহরণ:** ৩ নম্বর রো অ্যাক্সেস করতে চাইলে: `df.iloc[2]` (যেহেতু ইনডেক্স ০ থেকে শুরু হয়)।

### ২. `.loc[]` (Label-based Indexing)

যখন আপনি ইনডেক্সের **নাম বা লেবেল** (যেমন: 'row1', 'row2' বা নির্দিষ্ট আইডি) ব্যবহার করে রো অ্যাক্সেস করতে চান, তখন `loc` ব্যবহার করা হয়।

* **ব্যবহার:** `df.loc['row_label']`
* **উদাহরণ:** যদি ইনডেক্সের নাম হয় 'id_101', তবে: `df.loc['id_101']`।

### ৩. একাধিক রো একসাথে দেখা (Slicing)

আপনি যদি একটি রেঞ্জ বা নির্দিষ্ট কয়েকটি রো একসাথে দেখতে চান:

* **iloc দিয়ে:** `df.iloc[0:5]` (প্রথম ৫টি রো)।
* **loc দিয়ে:** `df.loc['start_label':'end_label']`।

# loc function

In [26]:
# Now we'll try to access the row and column of a dataframe. And the syntax is # df.loc[index start:index end, column_start, column_end]
# Accessing the first row of a dataframe

df_excel.loc[0]

StudentID                    PH1001
FullName                Alif Rahman
Data Structure Marks           85.0
Algorithm Marks                85.0
Python Marks                   88.0
CompletionStatus          Completed
EnrollmentDate           2024-01-15
Instructor                Mr. Karim
Location                      Dhaka
Name: 0, dtype: object

In [27]:
type(df_excel.loc[0])

pandas.Series

In [28]:
# Accessing some specific rows of a dataframe

df_excel.loc[[2, 4, 6, 8, 9]]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet

In [29]:
# Accessing some rows of a range of a dataframe

df_excel.loc[11:13]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi

In [30]:
# Accessing all values of a single column using loc function

df_excel.loc[:, 'Python Marks']

0     88.0
1      NaN
2     85.0
3     82.0
4     95.0
5     78.0
6      NaN
7     85.0
8     76.0
9     88.0
10    91.0
11    87.0
12    79.0
13     NaN
14    84.0
15     NaN
16    93.0
17    85.0
18     NaN
19    89.0
Name: Python Marks, dtype: float64

In [31]:
# Accessing all values of multiple columns using loc function

df_excel.loc[:, ['Python Marks', 'Algorithm Marks']]

    Python Marks  Algorithm Marks
0           88.0             85.0
1            NaN             92.0
2           85.0             88.0
3           82.0             78.0
4           95.0              NaN
5           78.0             75.0
6            NaN             80.0
7           85.0             81.0
8           76.0             72.0
9           88.0             89.0
10          91.0              NaN
11          87.0             85.0
12          79.0             75.0
13           NaN              NaN
14          84.0             86.0
15           NaN             94.0
16          93.0             90.0
17          85.0             88.0
18           NaN              NaN
19          89.0             86.0

In [32]:
# Accessing specific row values of specific columns using loc function

df_excel.loc[1:10, ['FullName', 'Algorithm Marks', 'CompletionStatus' ]]

            FullName  Algorithm Marks CompletionStatus
1      Fatima Akhter             92.0      In Progress
2      Imran Hossain             88.0        Completed
3   Jannatul Ferdous             78.0        Completed
4        Kamal Uddin              NaN      In Progress
5        Laila Begum             75.0        Completed
6     Mahmudul Hasan             80.0      In Progress
7        Nadia Islam             81.0        Completed
8         Omar Faruq             72.0        Completed
9       Priya Sharma             89.0        Completed
10      Rahim Sheikh              NaN      In Progress

# iloc function

In [33]:
# Now we'll try to access the row and column of a dataframe. And this time in a different way.

# Explicitly mentioning another column as the index

df_excel_StudentID_indexed = df_excel.set_index('StudentID')
# df_excel.set_index('StudentID', inplace=True)   # This inplace=True will actually modify the original dataframe df_excel. So we'll not perform this action unless it's necessary.

df_excel_StudentID_indexed

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [34]:
# Now look carefully; in this new dataframe, there is no numerical index at all, the index has already been modified. Therefore, loc function will not work for this dataframe anymore. Here comes the use of the 'iloc' function.

# Accessing specific row values of all columns using iloc function

df_excel_StudentID_indexed.iloc[2:8]

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram

In [35]:
# Accessing all row values of some specific columns using iloc function

df_excel_StudentID_indexed.iloc[:, 0:4]

,FullName,Data Structure Marks,Algorithm Marks,Python Marks
StudentID,,,,
PH1001,Alif Rahman,85.0,85.0,88.0
PH1002,Fatima Akhter,92.0,92.0,NaN
PH1003,Imran Hossain,88.0,88.0,85.0
PH1004,Jannatul Ferdous,78.0,78.0,82.0
PH1005,Kamal Uddin,NaN,NaN,95.0
PH1006,Laila Begum,75.0,75.0,78.0
PH1007,Mahmudul Hasan,80.0,80.0,NaN
PH1008,Nadia Islam,81.0,81.0,85.0
PH1009,Omar Faruq,72.0,72.0,76.0
PH1010,Priya Sharma,89.0,89.0,88.0
PH1011,Rahim Sheikh,NaN,NaN,91.0
PH1012,Sadia Chowdhury,85.0,85.0,87.0
PH1013,Tanvir Ahmed,75.0,75.0,79.0
PH1014,Urmi Akter,NaN,NaN,NaN
PH1015,Wahiduzzaman,86.0,86.0,84.0
PH1016,Ziaur Rahman,94.0,94.0,NaN
PH1017,Afsana Mimi,90.0,90.0,93.0
PH1018,Babul Ahmed,88.0,88.0,85.0
PH1019,Faria Rahman,NaN,NaN,NaN
PH1020,Nasir Khan,86.0,86.0,89.0

In [36]:
# Accessing some specific row values of some specific columns using iloc function

df_excel_StudentID_indexed.iloc[2:8, 0:4]

,FullName,Data Structure Marks,Algorithm Marks,Python Marks
StudentID,,,,
PH1003,Imran Hossain,88.0,88.0,85.0
PH1004,Jannatul Ferdous,78.0,78.0,82.0
PH1005,Kamal Uddin,NaN,NaN,95.0
PH1006,Laila Begum,75.0,75.0,78.0
PH1007,Mahmudul Hasan,80.0,80.0,NaN
PH1008,Nadia Islam,81.0,81.0,85.0

In [37]:
# Previously we've changed the indexing of the dataframe. Now we'll modify the column name.

# df_excel_StudentID_indexed_column_name_modified = df_excel_StudentID_indexed.rename(columns={
#     'FullName': 'Full Name',
#     'CompletionStatus': 'Completion Status',
#     'EnrollmentDate': 'Enrollment Date',
# })

df_excel_StudentID_indexed.rename(columns={
    'FullName': 'Full Name',
    'CompletionStatus': 'Completion Status',
    'EnrollmentDate': 'Enrollment Date',
}, inplace=True)    # This time we wanna do this modification in place.

df_excel_StudentID_indexed

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,Completion Status,Enrollment Date,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [38]:
# Deleting a row of a dataframe

df_excel.drop(0, inplace=True)      # Here 0 means row number. Inplace=True means we'll modify the original dataframe.'
df_excel

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [39]:
# Deleting a column of a dataframe

df_excel.drop('Instructor', axis=1, inplace=True)     # Here axis=1 means column. Inplace=True means we'll modify the original dataframe.'
df_excel

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [40]:
# Accessing and setting a value using loc function

df_excel.loc[1, 'Python Marks'] = 90
df_excel.loc[1, 'CompletionStatus'] = 'Completed'

df_excel

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,90.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [41]:
# Changing/updating/modifying some values all together

df_excel.loc[1:5, ['Python Marks', 'Algorithm Marks']] += 2
df_excel

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,94.0,92.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,90.0,87.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,80.0,84.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,97.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,77.0,80.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [42]:
# Iterating through the rows of a dataframe. This is just one way of iterating through a dataframe.

for index, row in df_excel.iterrows():
    print(index, row)
    print("--------------------------------------------------")

1 StudentID                      PH1002
FullName                Fatima Akhter
Data Structure Marks             92.0
Algorithm Marks                  94.0
Python Marks                     92.0
CompletionStatus            Completed
EnrollmentDate             2024-01-20
Location                   Chattogram
Name: 1, dtype: object
--------------------------------------------------
2 StudentID                      PH1003
FullName                Imran Hossain
Data Structure Marks             88.0
Algorithm Marks                  90.0
Python Marks                     87.0
CompletionStatus            Completed
EnrollmentDate             2024-02-10
Location                        Dhaka
Name: 2, dtype: object
--------------------------------------------------
3 StudentID                         PH1004
FullName                Jannatul Ferdous
Data Structure Marks                78.0
Algorithm Marks                     80.0
Python Marks                        84.0
CompletionStatus               Completed
EnrollmentDate                2024-02-12
Location                          Sylhet
Name: 3, dtype: object
--------------------------------------------------
4 StudentID                    PH1005
FullName                Kamal Uddin
Data Structure Marks            NaN
Algorithm Marks                 NaN
Python Marks                   97.0
CompletionStatus        In Progress
EnrollmentDate           2024-03-05
Location                 Chattogram
Name: 4, dtype: object
--------------------------------------------------
5 StudentID                    PH1006
FullName                Laila Begum
Data Structure Marks           75.0
Algorithm Marks                77.0
Python Marks                   80.0
CompletionStatus          Completed
EnrollmentDate           2024-03-08
Location                   Rajshahi
Name: 5, dtype: object
--------------------------------------------------
6 StudentID                       PH1007
FullName                Mahmudul Hasan
Data Structure Marks              80.0
Algorithm Marks                   80.0
Python Marks                       NaN
CompletionStatus           In Progress
EnrollmentDate              2024-04-01
Location                         Dhaka
Name: 6, dtype: object
--------------------------------------------------
7 StudentID                    PH1008
FullName                Nadia Islam
Data Structure Marks           81.0
Algorithm Marks                81.0
Python Marks                   85.0
CompletionStatus          Completed
EnrollmentDate           2024-04-22
Location                 Chattogram
Name: 7, dtype: object
--------------------------------------------------
8 StudentID                   PH1009
FullName                Omar Faruq
Data Structure Marks          72.0
Algorithm Marks               72.0
Python Marks                  76.0
CompletionStatus         Completed
EnrollmentDate          2024-05-16
Location                     Dhaka
Name: 8, dtype: object
--------------------------------------------------
9 StudentID                     PH1010
FullName                Priya Sharma
Data Structure Marks            89.0
Algorithm Marks                 89.0
Python Marks                    88.0
CompletionStatus           Completed
EnrollmentDate            2024-05-20
Location                      Sylhet
Name: 9, dtype: object
--------------------------------------------------
10 StudentID                     PH1011
FullName                Rahim Sheikh
Data Structure Marks             NaN
Algorithm Marks                  NaN
Python Marks                    91.0
CompletionStatus         In Progress
EnrollmentDate            2024-06-11
Location                      Khulna
Name: 10, dtype: object
--------------------------------------------------
11 StudentID                        PH1012
FullName                Sadia Chowdhury
Data Structure Marks               85.0
Algorithm Marks                    85.0
Python Marks                       87.0
CompletionStatus              Completed
EnrollmentDate               2024-06-14
Location                     Chattogram
Name: 11, dtype: object
--------------------------------------------------
12 StudentID                     PH1013
FullName                Tanvir Ahmed
Data Structure Marks            75.0
Algorithm Marks                 75.0
Python Marks                    79.0
CompletionStatus           Completed
EnrollmentDate            2024-07-02
Location                       Dhaka
Name: 12, dtype: object
--------------------------------------------------
13 StudentID                    PH1014
FullName                 Urmi Akter
Data Structure Marks            NaN
Algorithm Marks                 NaN
Python Marks                    NaN
CompletionStatus        Not Started
EnrollmentDate           2024-07-09
Location                   Rajshahi
Name: 13, dtype: str
--------------------------------------------------
14 StudentID                     PH1015
FullName                Wahiduzzaman
Data Structure Marks            86.0
Algorithm Marks                 86.0
Python Marks                    84.0
CompletionStatus           Completed
EnrollmentDate            2024-08-18
Location                       Dhaka
Name: 14, dtype: object
--------------------------------------------------
15 StudentID                     PH1016
FullName                Ziaur Rahman
Data Structure Marks            94.0
Algorithm Marks                 94.0
Python Marks                     NaN
CompletionStatus         In Progress
EnrollmentDate            2024-08-21
Location                  Chattogram
Name: 15, dtype: object
--------------------------------------------------
16 StudentID                    PH1017
FullName                Afsana Mimi
Data Structure Marks           90.0
Algorithm Marks                90.0
Python Marks                   93.0
CompletionStatus          Completed
EnrollmentDate           2025-09-01
Location                      Dhaka
Name: 16, dtype: object
--------------------------------------------------
17 StudentID                    PH1018
FullName                Babul Ahmed
Data Structure Marks           88.0
Algorithm Marks                88.0
Python Marks                   85.0
CompletionStatus          Completed
EnrollmentDate           2025-09-05
Location                     Sylhet
Name: 17, dtype: object
--------------------------------------------------
18 StudentID                     PH1019
FullName                Faria Rahman
Data Structure Marks             NaN
Algorithm Marks                  NaN
Python Marks                     NaN
CompletionStatus         Not Started
EnrollmentDate            2025-09-15
Location                  Chattogram
Name: 18, dtype: str
--------------------------------------------------
19 StudentID                   PH1020
FullName                Nasir Khan
Data Structure Marks          86.0
Algorithm Marks               86.0
Python Marks                  89.0
CompletionStatus         Completed
EnrollmentDate          2025-10-02
Location                     Dhaka
Name: 19, dtype: object
--------------------------------------------------

In [43]:
# Iterating through the rows of a dataframe. Now we'll see another way of doing this dataframe iteration.

# for i in df_excel.itertuples():
#     print(i)

for i in df_excel.itertuples(index=False):
    print(i)

Pandas(StudentID='PH1002', FullName='Fatima Akhter', _2=92.0, _3=94.0, _4=92.0, CompletionStatus='Completed', EnrollmentDate='2024-01-20', Location='Chattogram')
Pandas(StudentID='PH1003', FullName='Imran Hossain', _2=88.0, _3=90.0, _4=87.0, CompletionStatus='Completed', EnrollmentDate='2024-02-10', Location='Dhaka')
Pandas(StudentID='PH1004', FullName='Jannatul Ferdous', _2=78.0, _3=80.0, _4=84.0, CompletionStatus='Completed', EnrollmentDate='2024-02-12', Location='Sylhet')
Pandas(StudentID='PH1005', FullName='Kamal Uddin', _2=nan, _3=nan, _4=97.0, CompletionStatus='In Progress', EnrollmentDate='2024-03-05', Location='Chattogram')
Pandas(StudentID='PH1006', FullName='Laila Begum', _2=75.0, _3=77.0, _4=80.0, CompletionStatus='Completed', EnrollmentDate='2024-03-08', Location='Rajshahi')
Pandas(StudentID='PH1007', FullName='Mahmudul Hasan', _2=80.0, _3=80.0, _4=nan, CompletionStatus='In Progress', EnrollmentDate='2024-04-01', Location='Dhaka')
Pandas(StudentID='PH1008', FullName='Nadia Islam', _2=81.0, _3=81.0, _4=85.0, CompletionStatus='Completed', EnrollmentDate='2024-04-22', Location='Chattogram')
Pandas(StudentID='PH1009', FullName='Omar Faruq', _2=72.0, _3=72.0, _4=76.0, CompletionStatus='Completed', EnrollmentDate='2024-05-16', Location='Dhaka')
Pandas(StudentID='PH1010', FullName='Priya Sharma', _2=89.0, _3=89.0, _4=88.0, CompletionStatus='Completed', EnrollmentDate='2024-05-20', Location='Sylhet')
Pandas(StudentID='PH1011', FullName='Rahim Sheikh', _2=nan, _3=nan, _4=91.0, CompletionStatus='In Progress', EnrollmentDate='2024-06-11', Location='Khulna')
Pandas(StudentID='PH1012', FullName='Sadia Chowdhury', _2=85.0, _3=85.0, _4=87.0, CompletionStatus='Completed', EnrollmentDate='2024-06-14', Location='Chattogram')
Pandas(StudentID='PH1013', FullName='Tanvir Ahmed', _2=75.0, _3=75.0, _4=79.0, CompletionStatus='Completed', EnrollmentDate='2024-07-02', Location='Dhaka')
Pandas(StudentID='PH1014', FullName='Urmi Akter', _2=nan, _3=nan, _4=nan, CompletionStatus='Not Started', EnrollmentDate='2024-07-09', Location='Rajshahi')
Pandas(StudentID='PH1015', FullName='Wahiduzzaman', _2=86.0, _3=86.0, _4=84.0, CompletionStatus='Completed', EnrollmentDate='2024-08-18', Location='Dhaka')
Pandas(StudentID='PH1016', FullName='Ziaur Rahman', _2=94.0, _3=94.0, _4=nan, CompletionStatus='In Progress', EnrollmentDate='2024-08-21', Location='Chattogram')
Pandas(StudentID='PH1017', FullName='Afsana Mimi', _2=90.0, _3=90.0, _4=93.0, CompletionStatus='Completed', EnrollmentDate='2025-09-01', Location='Dhaka')
Pandas(StudentID='PH1018', FullName='Babul Ahmed', _2=88.0, _3=88.0, _4=85.0, CompletionStatus='Completed', EnrollmentDate='2025-09-05', Location='Sylhet')
Pandas(StudentID='PH1019', FullName='Faria Rahman', _2=nan, _3=nan, _4=nan, CompletionStatus='Not Started', EnrollmentDate='2025-09-15', Location='Chattogram')
Pandas(StudentID='PH1020', FullName='Nasir Khan', _2=86.0, _3=86.0, _4=89.0, CompletionStatus='Completed', EnrollmentDate='2025-10-02', Location='Dhaka')

# Sorting

In [44]:
# Sorting a dataframe according to the Python Marks in Ascending and Descending order

# df_excel.sort_values('Python Marks', ascending=True)      # Ascending order
df_excel.sort_values('Python Marks', ascending=False)       # Descending order

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
4,PH1005,Kamal Uddin,NaN,NaN,97.0,In Progress,2024-03-05,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
1,PH1002,Fatima Akhter,92.0,94.0,92.0,Completed,2024-01-20,Chattogram
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
2,PH1003,Imran Hossain,88.0,90.0,87.0,Completed,2024-02-10,Dhaka
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
3,PH1004,Jannatul Ferdous,78.0,80.0,84.0,Completed,2024-02-12,Sylhet
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
5,PH1006,Laila Begum,75.0,77.0,80.0,Completed,2024-03-08,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

In [45]:
# Sorting a dataframe according to multiple values

df_excel.sort_values(['Python Marks', 'Algorithm Marks'], ascending=[True, True])

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
5,PH1006,Laila Begum,75.0,77.0,80.0,Completed,2024-03-08,Rajshahi
3,PH1004,Jannatul Ferdous,78.0,80.0,84.0,Completed,2024-02-12,Sylhet
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
2,PH1003,Imran Hossain,88.0,90.0,87.0,Completed,2024-02-10,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
1,PH1002,Fatima Akhter,92.0,94.0,92.0,Completed,2024-01-20,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
4,PH1005,Kamal Uddin,NaN,NaN,97.0,In Progress,2024-03-05,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

# Filtering data based on condition

In [46]:
# Finding all student data where CompletionStatus = Not Started.

# df_excel.loc[df_excel['CompletionStatus'] == 'Not Started']
df_excel.loc[df_excel.CompletionStatus == 'Not Started']

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

In [47]:
# Finding all student data where CompletionStatus = Completed.

df_excel.loc[df_excel.CompletionStatus == 'Completed']

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,94.0,92.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,90.0,87.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,80.0,84.0,Completed,2024-02-12,Sylhet
5,PH1006,Laila Begum,75.0,77.0,80.0,Completed,2024-03-08,Rajshahi
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [48]:
# Finding all student data where CompletionStatus = Completed and Data Structure Marks >= 90.

# df_excel.loc[(df_excel.CompletionStatus == 'Completed') & (df_excel['Data Structure Marks'] >= 90)]
df_excel.loc[(df_excel['CompletionStatus'] == 'Completed') & (df_excel['Data Structure Marks'] >= 90)]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,94.0,92.0,Completed,2024-01-20,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka

# Solution of the LEETCODE problem: 595. Big Countries
Url: https://leetcode.com/problems/big-countries/description/?envType=study-plan-v2&envId=30-days-of-pandas&lang=pythondata

In [49]:
# Creating the array with an 'object' dtype and with the exact given data in the problem description
world_array = np.array([
    ['Afghanistan', 'Asia', 652230, 25500100, 20343000000],
    ['Albania', 'Europe', 28748, 2831741, 12960000000],
    ['Algeria', 'Africa', 2381741, 37100000, 188681000000],
    ['Andorra', 'Europe', 468, 78115, 3712000000],
    ['Angola', 'Africa', 1246700, 20609294, 100990000000]
], dtype=object)


# world_array
# type(world_array)


# Now converting the array into a dataframe
world = pd.DataFrame(world_array, columns=['name', 'continent', 'area', 'population', 'gdp'])
# world
# type(world)


# The given function in the problem description
def big_countries(world: pd.DataFrame) -> pd.DataFrame:

    # Filter the dataframe based on the given conditions
    big_country = world.loc[(world['area'] >= 3000000) | (world['population'] >= 25000000)]

    # Select only the name, population and area columns as per the requirement
    result = big_country[['name', 'population', 'area']]

    # Return the result dataframe
    return result


big_countries(world)

          name population     area
0  Afghanistan   25500100   652230
2      Algeria   37100000  2381741

In [52]:
# Creating the array with an 'object' dtype and with the exact given data in the problem description
world_array = np.array([
    ['Afghanistan', 'Asia', 652230, 25500100, 20343000000],
    ['Albania', 'Europe', 28748, 2831741, 12960000000],
    ['Algeria', 'Africa', 2381741, 37100000, 188681000000],
    ['Andorra', 'Europe', 468, 78115, 3712000000],
    ['Angola', 'Africa', 1246700, 20609294, 100990000000]
], dtype=object)


# world_array
# type(world_array)


# Now converting the array into a dataframe
world = pd.DataFrame(world_array, columns=['name', 'continent', 'area', 'population', 'gdp'])
# world
# type(world)


# The given function in the problem description
def big_countries(world: pd.DataFrame) -> pd.DataFrame:
    return world.loc[(world['area'] >= 3000000) | (world['population'] >= 25000000), ['name', 'population', 'area']]


big_countries(world)

          name population     area
0  Afghanistan   25500100   652230
2      Algeria   37100000  2381741

# Solution of the LEETCODE problem: 1757. Recyclable and Low Fat Products
Url: https://leetcode.com/problems/recyclable-and-low-fat-products/description/

In [7]:
# Creating the array with an 'object' dtype and with the exact given data in the problem description
products_array = np.array([
    [0, 'Y', 'N'],
    [1, 'Y', 'Y'],
    [2, 'N', 'Y'],
    [3, 'Y', 'Y'],
    [4, 'N', 'N']
], dtype=object)


# products_array
# type(world_array)


# Now converting the array into a dataframe
products = pd.DataFrame(products_array, columns=['product_id', 'low_fats', 'recyclable'])
# products
# type(products)


# The given function in the problem description
def find_products(products: pd.DataFrame) -> pd.DataFrame:

    # Filter the dataframe based on the given conditions and select only the product_id column as per the requirement
    low_fat_and_recyclable = products.loc[(products['low_fats'] == 'Y') & (products['recyclable'] == 'Y'), ['product_id']]

    # Return the result dataframe
    return low_fat_and_recyclable


find_products(products)

  product_id
1          1
3          3

---