In [1]:
import numpy as np
import pandas as pd
from pandas import col

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Sakib"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston",
             "H Los Ang"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000, 70000]
}

df = pd.DataFrame(data)
df

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

In [2]:
# Finding city names which contains the word 'New'

df.loc[df['City'].str.contains('New')]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [3]:
# Finding city names which contains the word 'new'
df.loc[df['City'].str.contains('new')]

Empty DataFrame
Columns: [Name, City, Department, Salary]
Index: []

In [4]:
# Finding city names which contains the word 'new', but this time ignore the case sensitivity

df.loc[df['City'].str.contains('new', case=False)]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [5]:
# We also can use a complex regex expression to find a custom match instead of only a simple keyword.
# Finding city names which start with 'Los'.

df.loc[df['City'].str.contains(r'^Los', case=False)]

  Name         City Department  Salary
1  Bob  Los Angeles         IT   60000

In [6]:
# Finding city names which start with 'Los'.

df.loc[df['City'].str.contains(r'rk$', case=False)]

      Name      City Department  Salary
0    Alice  New York         HR   50000
2  Charlie    Newark    Finance   55000

In [7]:
# # Finding names which start with vowels.

df.loc[df['Name'].str.contains(r'^[AEIOU]', case=False)]

    Name       City Department  Salary
0  Alice   New York         HR   50000
4    Eve  New Delhi         HR   52000

In [8]:
# Finding city names which contains 'New' or 'Los'.

df.loc[df['City'].str.contains(r'(?:New|Los)', case=False, na=False)]   # na=False prevents issues if there are missing values (NaN) in City

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000
8    Sakib    H Los Ang         HR   70000

# Adding a New Column in a DataFrame

In [9]:
# Reading a CSV file into a DataFrame

student_data_df = pd.read_csv("student_data.csv")
student_data_df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Adding a column with constant values

student_data_df['Country'] = 'Bangladesh'
student_data_df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh

In [11]:
# Adding a new column with dynamically calculated values

student_data_df['Total Marks'] = student_data_df['Data Structure Marks'] + student_data_df['Algorithm Marks'] + student_data_df['Python Marks']
student_data_df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN

In [12]:
# We will create a new column and will calculate the grade based on the Data Structure Marks

student_data_df['A+ in DS'] = np.where(student_data_df['Data Structure Marks'] > 90, 'A+', 'A')
student_data_df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN,A

In [13]:
# We'll create a new column and will mention if the respective

# student_data_df['Passed in DS'] = np.where(student_data_df['Data Structure Marks'] > 70, True, False)
student_data_df['Passed in DS'] = student_data_df['Data Structure Marks'] > 70
student_data_df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN,A,False

In [14]:
# Now we'll create anew column 'First Name', then will split the FullName of the dataFrame, and then will add the 1st split part into the 'First Name'

student_data_df['First Name'] = student_data_df['FullName'].str.split(' ').str[0]
student_data_df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False,Kamal
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True,Mahmudul
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False,Rahim
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False,Urmi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Ziaur
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False,Faria
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN,A,False,NaN

In [15]:
student_data_df1 = pd.read_csv("student_data.csv")
student_data_df1

# That means whatever modifications we have done so far are not saved in the main .csv file.

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# Now we'll save the modified DataFrame into a separate .csv file.
student_data_df.to_csv("student_data_v1.csv")


# And then again we'll read the .csv file and will check if the modified version of the DataFrame has been saved or not.
student_data_df2 = pd.read_csv("student_data_v1.csv")
student_data_df2

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima
2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False,Kamal
5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True,Mahmudul
7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False,Rahim
11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False,Urmi
14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Ziaur
16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False,Faria
19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir
20,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN,A,False,NaN

# Unique and nunique

In [17]:
data1 = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 85, 95, 90]
}

df1 = pd.DataFrame(data1)
df1

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     85
4    David     Tokyo     95
5      Bob    London     90

In [18]:
# Finding unique values of a column

df1['Name'].unique()

<ArrowStringArray>
['Alice', 'Bob', 'Charlie', 'David']
Length: 4, dtype: str

In [19]:
# Finding the count of unique names

len(df1['Name'].unique())

4

In [20]:
# Finding how many unique Data Structure marks we have.

student_data_df2['Data Structure Marks'].unique()

# Look carefully, here we one NaN among all the values, and this will make the count wrong.

array([85., 92., 88., 78., nan, 75., 80., 81., 72., 89., 86., 94., 90.])

In [21]:
# The count of unique Data Structure Marks

len(student_data_df2['Data Structure Marks'].unique())

# And the count is including NaN, which is not the correct counting.

13

In [22]:
# Now we'll see how we can avoid NaN value while accessing and analyzing DataFrame values
# Finding how many unique Data Structure marks we have.

student_data_df2['Data Structure Marks'].nunique()  # nunique doesn't count Null values

# Now this count is giving us the right value.
# Unique works only with Pandas Series.

12

In [23]:
student_data_df.nunique()

StudentID               20
FullName                20
Data Structure Marks    12
Algorithm Marks         12
Python Marks            12
CompletionStatus         3
EnrollmentDate          20
Instructor               3
Location                 5
Country                  1
Total Marks             11
A+ in DS                 2
Passed in DS             2
First Name              20
dtype: int64

In [24]:
df.nunique()

Name          9
City          9
Department    4
Salary        8
dtype: int64

In [25]:
df1.nunique()

Name     4
City     4
Score    4
dtype: int64

# Check Null

In [26]:
# Checking where the values are missing or have null value in a DataFrame.

student_data_df.isnull()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,True,True,False,False,False,False,False,False,True,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,True,False,False,False,False,False,True,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,True,True,False,False,False,False,False,False,True,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,True,True,True,False,False,False,False,False,True,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,True,False,False,False,False,False,True,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,True,True,True,False,False,False,False,False,True,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,True,True,True,True,True,True,True,True,True,False,True,False,False,True

In [27]:
# Checking where the values are missing or have null value in a column of a DataFrame.

student_data_df['Data Structure Marks'].isnull()

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18     True
19    False
20     True
Name: Data Structure Marks, dtype: bool

In [28]:
# Checking where the values are missing or have null value in a column of a DataFrame.

student_data_df['Data Structure Marks'].notnull()

0      True
1      True
2      True
3      True
4     False
5      True
6      True
7      True
8      True
9      True
10    False
11     True
12     True
13    False
14     True
15     True
16     True
17     True
18    False
19     True
20    False
Name: Data Structure Marks, dtype: bool

In [29]:
# Checking if there is at least one null value in a column of a DataFrame.

# student_data_df['Data Structure Marks'].hasnans
# student_data_df['Python Marks'].hasnans
# student_data_df['Algorithm Marks'].hasnans
student_data_df['StudentID'].hasnans
# student_data_df

True

In [30]:
# Now we'll check if there is at least one null value in a DataFrame. If yes, then which row?'

student_data_df.loc[student_data_df["StudentID"].isna(), ["StudentID", "FullName"]]

   StudentID FullName
20       NaN      NaN

# Handling Duplicate Values

In [31]:
data2 = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 70, 95, 90]
}

df2 = pd.DataFrame(data2)
df2

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95
5      Bob    London     90

In [32]:
# Now finding duplicate rows from the DataFrame

df2.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [33]:
# Now finding the total number of duplicate rows

print(df2.duplicated().sum())

1

In [34]:
# Now removing duplicate rows from the DataFrame. It returns only a copy without modifying the original DataFrame.

df2.drop_duplicates()

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [35]:
# Now we'll remove the duplicate rows from the original DataFrame.

df2.drop_duplicates(inplace=True)
print(df2.duplicated().sum())
# df2.duplicated()
df2

0

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [36]:
# Now we'll find duplicates only based on a specific column, rather than a full row.

# print(df2.duplicated(subset=['Name']).sum())
df2.duplicated(subset=['Name'])

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [37]:
df2.duplicated(subset=['City'])

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [38]:
df2.duplicated(subset=['Score'])

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [39]:
# Generally, the .drop_duplicates function keeps the first data among the duplicates and remove the last one.
# But we can change this by keeping the last one and removing the first one.

df2.drop_duplicates(subset=['Name'], keep='last')   # Keeping the last value and removing the first value
# df2.drop_duplicates(subset=['Name'], keep='first')    # Keeping the first value and removing the last value

      Name      City  Score
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

# Handling Null values

#### Fill all missing values with 0
df_filled = df.fillna(0)

#### Fill different values for different columns
df_filled = df.fillna({'A': 0, 'B': 99, 'C': 'Unknown'})

#### Forward fill - This method propagates the last valid observation forward to next missing value
df_ffilled = df.ffill()

#### Backward fill - This method uses the next valid observation to fill the gap.
df_bfilled = df.bfill()

#### You can fill missing values with statistical measures like mean, median, or mode.
df['A'].fillna(df['A'].mean(), inplace=True)
df['B'].fillna(df['B'].median(), inplace=True)

In [40]:
student_data_df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False,Kamal
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True,Mahmudul
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False,Rahim
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False,Urmi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Ziaur
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False,Faria
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN,A,False,NaN

In [41]:
# Now we'll all the rows, that contains at least a Null/NaN value, in any column of the DataFrame.
# It doesn't remove the Null/NaN value consisting rows from the original DataFrame.

student_data_df.dropna()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir

In [42]:
# We can select a condition on when to delete a row. Wither when at least one value is NaN, or when all values in a row are NaN.

# student_data_df.dropna(how='any')   # When any one of the values is NaN.
# student_data_df.dropna(how='all')   # When all the values of a row are NaN.
student_data_df.dropna(how='all', inplace=True)   # Remove the row when all the values of a row are NaN and save this in the original DataFrame.
student_data_df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False,Kamal
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True,Mahmudul
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False,Rahim
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False,Urmi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Ziaur
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False,Faria
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN,A,False,NaN

In [43]:
# Now we'll find the rows where Python Marks are NaN and will remove those rows.

student_data_df.dropna(subset=['Python Marks'])
# student_data_df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False,Kamal
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False,Rahim
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir

In [44]:
# Now we'll find the rows where Python Marks and Algorithm Marks are NaN and will remove those rows.

student_data_df.dropna(subset=['Python Marks', 'Algorithm Marks'])
# student_data_df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir

In [45]:
# Now we'll fill up the NaN values with let's say 0.

student_data_df.fillna(0)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
1,PH1002,Fatima Akhter,92.0,92.0,0.0,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,0.0,A+,True,Fatima
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,PH1005,Kamal Uddin,0.0,0.0,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,0.0,A,False,Kamal
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
6,PH1007,Mahmudul Hasan,80.0,80.0,0.0,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,0.0,A,True,Mahmudul
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,PH1011,Rahim Sheikh,0.0,0.0,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,0.0,A,False,Rahim
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
13,PH1014,Urmi Akter,0.0,0.0,0.0,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,0.0,A,False,Urmi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
15,PH1016,Ziaur Rahman,94.0,94.0,0.0,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,0.0,A+,True,Ziaur
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
18,PH1019,Faria Rahman,0.0,0.0,0.0,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,0.0,A,False,Faria
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir
20,0,0,0.0,0.0,0.0,0,0,0,0,Bangladesh,0.0,A,False,0

In [46]:
# Changing all NaN values to 0 is not ideal because not all columns have the same data type. So we also need to change values by column.

student_data_df['FullName'].fillna('Unknown')

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
20             Unknown
Name: FullName, dtype: str

In [47]:
# Now we'll change the value of another column, where the data type is different.

student_data_df['Data Structure Marks'].fillna(0)

0     85.0
1     92.0
2     88.0
3     78.0
4      0.0
5     75.0
6     80.0
7     81.0
8     72.0
9     89.0
10     0.0
11    85.0
12    75.0
13     0.0
14    86.0
15    94.0
16    90.0
17    88.0
18     0.0
19    86.0
20     0.0
Name: Data Structure Marks, dtype: float64

In [48]:
# Or we can change the NaN values with the average of that specific column.

# student_data_df['Data Structure Marks'].fillna(student_data_df['Data Structure Marks'].mean())
# student_data_df['Algorithm Marks'].fillna(student_data_df['Algorithm Marks'].mean())
student_data_df['Python Marks'].fillna(student_data_df['Python Marks'].mean())

0     88.000000
1     85.666667
2     85.000000
3     82.000000
4     95.000000
5     78.000000
6     85.666667
7     85.000000
8     76.000000
9     88.000000
10    91.000000
11    87.000000
12    79.000000
13    85.666667
14    84.000000
15    85.666667
16    93.000000
17    85.000000
18    85.666667
19    89.000000
20    85.666667
Name: Python Marks, dtype: float64

# Statistical Functions

In [49]:
# Let's see the original DataFrame again, with all NaN rows removed.

student_data_df.dropna()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir

In [50]:
# Now le's say we wanna see the sum of the 'Data Structure Marks' column.

student_data_df['Data Structure Marks'].sum()       # np.float64(1344.0)
print(student_data_df['Data Structure Marks'].sum())

1344.0

In [51]:
# Now we'll find the minimum value of the 'Data Structure Marks' column.

student_data_df['Data Structure Marks'].min()

np.float64(72.0)

In [52]:
# Now we'll find the maximum value of the 'Data Structure Marks' column.

student_data_df['Data Structure Marks'].max()

np.float64(94.0)

In [53]:
# Now we'll find the mean/average value of the 'Data Structure Marks' column.

student_data_df['Data Structure Marks'].mean()

np.float64(84.0)

In [54]:
# Now we'll find the median value of the 'Data Structure Marks' column.

student_data_df['Data Structure Marks'].median()

np.float64(85.5)

In [55]:
# Mode: The value, that appears most often in a set of data.
# Now we'll find the mode value of the 'Data Structure Marks' column.

student_data_df['Data Structure Marks'].mode()

0    75.0
1    85.0
2    86.0
3    88.0
Name: Data Structure Marks, dtype: float64

In [56]:
# Standard deviation: It is a statistical measure of how spread-out numbers are in a data set.
# It represents the average distance between each data point and the mean (average).
# Now we'll find the Standard deviation value of the 'Data Structure Marks' column.

student_data_df['Data Structure Marks'].std()

np.float64(6.501281924871945)

In [57]:
# Correlation Matrix: A correlation matrix is a table, often visualized as a heatmap, that displays the correlation coefficients between multiple variables in a dataset.

student_data_df[['Data Structure Marks', 'Python Marks']].corr()

# The output values range from -1 to +1:
# +1 means the two marks increase/decrease together perfectly (strong positive relationship),
#  0 means no linear relationship,
# -1 means one increases while the other decreases perfectly (strong negative relationship).
# The diagonal will always be 1.0 because each column is perfectly correlated with itself.

                      Data Structure Marks  Python Marks
Data Structure Marks              1.000000      0.893455
Python Marks                      0.893455      1.000000

In [58]:
# Now we'll find the sum of different columns. It will add all the values of the columns together. It's also called axis sum or axis = 0.

student_data_df[['Data Structure Marks', 'Python Marks', 'Algorithm Marks']].sum()

Data Structure Marks    1344.0
Python Marks            1285.0
Algorithm Marks         1344.0
dtype: float64

In [59]:
# If we want to get the sum of all 3 columns rowwise, then we'll use axis = 1.

student_data_df[['Data Structure Marks', 'Python Marks', 'Algorithm Marks']].sum(axis=1)

0     258.0
1     184.0
2     261.0
3     238.0
4      95.0
5     228.0
6     160.0
7     247.0
8     220.0
9     266.0
10     91.0
11    257.0
12    229.0
13      0.0
14    256.0
15    188.0
16    273.0
17    261.0
18      0.0
19    261.0
20      0.0
dtype: float64

In [60]:
# Now we'll use some other functions, in axis=1, just like sum().

# student_data_df[['Data Structure Marks', 'Python Marks', 'Algorithm Marks']].max(axis=1)
# student_data_df[['Data Structure Marks', 'Python Marks', 'Algorithm Marks']].min(axis=1)
# student_data_df[['Data Structure Marks', 'Python Marks', 'Algorithm Marks']].mean(axis=1)
student_data_df[['Data Structure Marks', 'Python Marks', 'Algorithm Marks']].median(axis=1)

0     85.0
1     92.0
2     88.0
3     78.0
4     95.0
5     75.0
6     80.0
7     81.0
8     72.0
9     89.0
10    91.0
11    85.0
12    75.0
13     NaN
14    86.0
15    94.0
16    90.0
17    88.0
18     NaN
19    86.0
20     NaN
dtype: float64

In [61]:
# Now we'll create a new column 'Total Marks' and will add the sum of all 3 columns.
# student_data_df['Total Marks'] = student_data_df[['Data Structure Marks', 'Python Marks', 'Algorithm Marks']].sum(axis=1)

# Another way to do it is:
# student_data_df['Total Marks'] = pd.concat([student_data_df['Data Structure Marks'], student_data_df['Python Marks'], student_data_df['Algorithm Marks']], axis=1).sum(axis=1)

# Another way to do it is:
student_data_df['Total Marks'] = student_data_df.iloc[:, 2:5].sum(axis=1)

# Now I want to drop the column 'Total Marks' from the DataFrame and try it again.
# student_data_df.drop(columns=['Total Marks'], inplace=True)

student_data_df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,184.0,A+,True,Fatima
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,95.0,A,False,Kamal
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,160.0,A,True,Mahmudul
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,91.0,A,False,Rahim
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,0.0,A,False,Urmi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,188.0,A+,True,Ziaur
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,0.0,A,False,Faria
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,0.0,A,False,NaN

In [62]:
# we also can get statistical values using .describe() function.
student_data_df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks  Total Marks
count             16.000000        16.000000     15.000000    21.000000
mean              84.000000        84.000000     85.666667   189.190476
std                6.501282         6.501282      5.394000    94.532333
min               72.000000        72.000000     76.000000     0.000000
25%               79.500000        79.500000     83.000000   160.000000
50%               85.500000        85.500000     85.000000   229.000000
75%               88.250000        88.250000     88.500000   258.000000
max               94.000000        94.000000     95.000000   273.000000

# Applying function on DataFrame

In [63]:
student_data_df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,184.0,A+,True,Fatima
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,95.0,A,False,Kamal
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,160.0,A,True,Mahmudul
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,91.0,A,False,Rahim
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,0.0,A,False,Urmi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,188.0,A+,True,Ziaur
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,0.0,A,False,Faria
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,0.0,A,False,NaN

### Pandas-এ ফাংশন অ্যাপ্লাই
Pandas-এ DataFrame-এর ওপর কাস্টম ফাংশন অ্যাপ্লাই করা যায় এবং এটি ডাটা ম্যানিপুলেশনের জন্য অত্যন্ত শক্তিশালী একটি টুল। Pandas-এ কোনো নির্দিষ্ট রো (Row) বা কলামের (Column) ওপর নিজের তৈরি করা কোনো লজিক চালানোর জন্য .apply() মেথড ব্যবহার করা হয়। এটি লুপ (For Loop) চালানোর চেয়ে অনেক দ্রুত এবং ক্লিন।

### কেন .apply() ব্যবহার করবেন?
##### (1) যখন Pandas-এর বিল্ট-ইন কোনো মেথড (যেমন: mean, sum) দিয়ে আপনার কাজ হচ্ছে না।
##### (2) যখন ডাটার ওপর জটিল কোনো কন্ডিশন অ্যাপ্লাই করতে হচ্ছে।

### আপনি দুইভাবে ফাংশন ব্যবহার করতে পারেন:
##### (1) Normal Function: বড় লজিকের জন্য।
##### (2) Lambda Function: ছোট এক লাইনের লজিকের জন্য।

### Scaling করা কি কোনো ফাংশন?
প্রযুক্তিগতভাবে বলতে গেলে, Scaling একটি গাণিতিক প্রক্রিয়া বা Transformation, কোনো বিল্ট-ইন ফাংশন নয়। তবে এটি করার জন্য আমরা ফাংশন ব্যবহার করি।

### কেন করা হয়? (Why is Scaling important?)
##### (1) Algorithm Performance: অনেক Machine Learning অ্যালগরিদম (যেমন: KNN, SVM, K-Means) দূরত্বের ওপর ভিত্তি করে কাজ করে। বড় ভ্যালু থাকলে অ্যালগরিদম মনে করে সেই কলামটি বেশি গুরুত্বপূর্ণ, যা ভুল রেজাল্ট দিতে পারে।
##### (2) Fast Convergence: Gradient Descent ভিত্তিক অ্যালগরিদমগুলো Scaling করা থাকলে খুব দ্রুত রেজাল্ট দিতে পারে।
##### (3) Fair Comparison: বিভিন্ন এককের ডাটাকে (কেজি, মিটার, টাকা) সমান গুরুত্ব দেওয়ার জন্য এটি প্রয়োজন।

## 📐 Data Scaling Methods: বিস্তারিত নোট

যখন আপনার ডাটাসেটের বিভিন্ন **Features** বা কলামের ভ্যালু রেঞ্জ আলাদা হয়, তখন সেগুলোকে একটি নির্দিষ্ট মাপে নিয়ে আসাকেই **Scaling** বলে। এর প্রধান পদ্ধতিগুলো নিচে আলোচনা করা হলো:

### ১. Normalization (Min-Max Scaling)

এই পদ্ধতিতে ডাটার সর্বনিম্ন মানকে **0** এবং সর্বোচ্চ মানকে **1** ধরে বাকি সব ভ্যালুকে এই সীমার মধ্যে নিয়ে আসা হয়।

* **কখন ব্যবহার করবেন:** যখন আপনি জানেন যে আপনার ডাটা কোনো নির্দিষ্ট **Distribution** (যেমন: Gaussian distribution) মেনে চলে না। ইমেজ প্রসেসিং বা এমন অ্যালগরিদম যেখানে দূরত্বের হিসাব আছে (যেমন: KNN) সেখানে এটি খুব কার্যকর।
* **সীমাবদ্ধতা:** এটি **Outliers** (অস্বাভাবিক মান) দ্বারা খুব বেশি প্রভাবিত হয়।

### ২. Standardization (Z-score Normalization)

এই পদ্ধতিতে ডাটার **Mean** (গড়) করা হয় **0** এবং **Standard Deviation** করা হয় **1**। এর ফলে ডাটা একটি স্ট্যান্ডার্ড নরমাল ডিস্ট্রিবিউশনে রূপান্তরিত হয়।

* **কখন ব্যবহার করবেন:** যখন আপনার মেশিন লার্নিং মডেল (যেমন: Logistic Regression, SVM বা Linear Regression) ডাটা নরমাল ডিস্ট্রিবিউশনে আছে বলে ধরে নেয়।
* **সুবিধা:** এটি **Outliers** থাকলেও ডাটার মূল বৈশিষ্ট্য খুব একটা নষ্ট করে না।

### ৩. Robust Scaling

যদি আপনার ডাটাসেটে প্রচুর পরিমাণে **Outliers** থাকে, তবে **Min-Max** বা **Standard Scaling** ভালো কাজ করে না। সেক্ষেত্রে **Robust Scaling** ব্যবহার করা হয়। এটি **Mean** বা **Max** ভ্যালুর বদলে **Median** এবং **Interquartile Range (IQR)** ব্যবহার করে ডাটা স্কেল করে।

* **সুবিধা:** এটি আউটলায়ারের প্রতি অনেক বেশি সহনশীল।

### ৪. Power Transformer / Log Transformation

অনেক সময় ডাটা খুব বেশি একপেশে (Skewed) থাকে। এই পদ্ধতিগুলো ব্যবহার করে ডাটার **Skewness** কমানো হয় এবং ভ্যারিয়েন্সকে স্থিতিশীল করা হয়।


### 📌 মূল পার্থক্য একনজরে:

| বৈশিষ্ট্য | Normalization | Standardization | Robust Scaling |
| --- | --- | --- | --- |
| **Range** | সাধারণত 0 থেকে 1 | কোনো নির্দিষ্ট সীমা নেই | কোনো নির্দিষ্ট সীমা নেই |
| **Mean** | নির্ধারিত নয় | সবসময় 0 হয় | নির্ধারিত নয় |
| **Outliers** | খুব বেশি প্রভাবিত হয় | কিছুটা প্রভাবিত হয় | সবচেয়ে কম প্রভাবিত হয় |

---

**মনে রাখবেন:** মডেল ট্রেনিং করার আগে সবসময় ডাটা স্কেলিং করা উচিত, বিশেষ করে যদি আপনি **Distance-based** বা **Gradient Descent** ভিত্তিক অ্যালগরিদম ব্যবহার করেন।

In [64]:
# Now we'll do the MinMax Scaling on the Total Marks of the DataFrame.


# First, we'll find the minimum and maximum values of the 'Total Marks' column.
mx = student_data_df['Total Marks'].max()
mn = student_data_df['Total Marks'].min()


# Then, this is one way of scaling the 'Total Marks' column:
# student_data_df['Scaled Total Marks'] = (student_data_df['Total Marks'] - mn) / (mx - mn)


# Now this is another way of scaling the 'Total Marks' column:
customBuildFunction = lambda x: (x - mn) / (mx - mn)
student_data_df['Scaled Total Marks'] = student_data_df['Total Marks'].apply(customBuildFunction)


# We can remove the 'Scaled Total Marks' column from the DataFrame and try it again.
# student_data_df.drop(columns=['Scaled Total Marks'], inplace=True)


# Let's see the DataFrame again.
student_data_df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name,Scaled Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif,0.945055
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,184.0,A+,True,Fatima,0.673993
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran,0.956044
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul,0.871795
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,95.0,A,False,Kamal,0.347985
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila,0.835165
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,160.0,A,True,Mahmudul,0.586081
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia,0.904762
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar,0.805861
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya,0.974359
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,91.0,A,False,Rahim,0.333333
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia,0.941392
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir,0.838828
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,0.0,A,False,Urmi,0.000000
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman,0.937729
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,188.0,A+,True,Ziaur,0.688645
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana,1.000000
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul,0.956044
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,0.0,A,False,Faria,0.000000
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir,0.956044
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,0.0,A,False,NaN,0.000000

In [65]:
# Now we'll build and use another custom function to grade the students based on their Total Marks.

def grading_system(total_mark):
    if total_mark >= 260:
        return 'A+'
    elif total_mark >= 250:
        return 'A'
    elif total_mark >= 240:
        return 'A-'
    else:
        return 'B'

student_data_df['Grade'] = student_data_df['Total Marks'].apply(grading_system)
student_data_df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name,Scaled Total Marks,Grade
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif,0.945055,A
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,184.0,A+,True,Fatima,0.673993,B
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran,0.956044,A+
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul,0.871795,B
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,95.0,A,False,Kamal,0.347985,B
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila,0.835165,B
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,160.0,A,True,Mahmudul,0.586081,B
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia,0.904762,A-
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar,0.805861,B
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya,0.974359,A+
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,91.0,A,False,Rahim,0.333333,B
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia,0.941392,A
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir,0.838828,B
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,0.0,A,False,Urmi,0.000000,B
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman,0.937729,A
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,188.0,A+,True,Ziaur,0.688645,B
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana,1.000000,A+
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul,0.956044,A+
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,0.0,A,False,Faria,0.000000,B
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir,0.956044,A+
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,0.0,A,False,NaN,0.000000,B

In [66]:
# Now we'll build and use another custom function on the complete DataFrame.


def marking_system(data_frame):
    a = data_frame['Data Structure Marks'] * 2
    b = data_frame['Python Marks'] * 3
    c = data_frame['Algorithm Marks'] * 4
    return a + b + c


student_data_df['Multiplied_by_2_3_4 Marks'] = student_data_df.apply(marking_system, axis=1)    # As we are doing the summation rowwise, we'll use axis = 1.
student_data_df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name,Scaled Total Marks,Grade,Multiplied_by_2_3_4 Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif,0.945055,A,774.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,184.0,A+,True,Fatima,0.673993,B,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran,0.956044,A+,783.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul,0.871795,B,714.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,95.0,A,False,Kamal,0.347985,B,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila,0.835165,B,684.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,160.0,A,True,Mahmudul,0.586081,B,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia,0.904762,A-,741.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar,0.805861,B,660.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya,0.974359,A+,798.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,91.0,A,False,Rahim,0.333333,B,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia,0.941392,A,771.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir,0.838828,B,687.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,0.0,A,False,Urmi,0.000000,B,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman,0.937729,A,768.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,188.0,A+,True,Ziaur,0.688645,B,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana,1.000000,A+,819.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul,0.956044,A+,783.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,0.0,A,False,Faria,0.000000,B,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir,0.956044,A+,783.0
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,0.0,A,False,NaN,0.000000,B,NaN

---
### ১. Datetime কী? (What is Datetime?)

**Datetime** হলো একটি নির্দিষ্ট মুহূর্তের তারিখ এবং সময়ের প্রকাশ। এটি মূলত `Year-Month-Day Hour:Minute:Second` ফরম্যাটে থাকে।

* **ব্যবহার:** কোনো ট্রানজ্যাকশন কখন হয়েছে বা কোনো ইভেন্টের নির্দিষ্ট সময় রেকর্ড করতে এটি ব্যবহৃত হয়।
* **Pandas Command:** স্ট্রিং থেকে তারিখ বানাতে `pd.to_datetime()` ব্যবহার করা হয়।

**Datetime-এর প্রধান কাজসমূহ:**

* তারিখ থেকে দিন (`.dt.day`), মাস (`.dt.month`), বছর (`.dt.year`) আলাদা করা।
* সপ্তাহের নাম (`.dt.day_name()`) বা মাসের নাম বের করা।
* দিনের নাম বা ছুটির দিন কি না তা চেক করা।

---

### ২. Timedelta কী? (What is Timedelta?)

**Timedelta** হলো সময়ের একটি ব্যবধান বা ডিউরেশন (Duration)। এটি কোনো নির্দিষ্ট তারিখ নয়, বরং দুটি তারিখের মধ্যবর্তী সময়ের পার্থক্য।

* **ব্যবহার:** বয়স হিসাব করা, একটি কাজ শেষ হতে কত সময় লাগলো তা বের করা, অথবা আগামী ১০ দিন পর কী তারিখ হবে তা বের করা।
* **Pandas Command:** `pd.to_timedelta()` অথবা দুটি **Datetime** বিয়োগ করে এটি পাওয়া যায়।

**Timedelta-এর প্রধান কাজসমূহ:**

* তারিখের সাথে সময় যোগ বা বিয়োগ করা (যেমন: আজকের তারিখ + ৫ দিন)।
* মোট কত সেকেন্ড বা কত ঘণ্টা পার হয়েছে তা বের করা।

---

### ৩. মূল পার্থক্য একনজরে (Key Differences)

| বৈশিষ্ট্য | Datetime | Timedelta |
| --- | --- | --- |
| **মূল ধারণা** | ক্যালেন্ডারের একটি নির্দিষ্ট দিন/সময়। | সময়ের একটি পরিমাপ বা গ্যাপ। |
| **উদাহরণ** | ২০ মে, ২০২৪। | ৫ দিন ১০ ঘণ্টা। |
| **গাণিতিক কাজ** | `Date1 - Date2 = Timedelta` | `Date1 + Timedelta = New Date` |

**প্রো-টিপ:** যখনই কোনো CSV ফাইল রিড করবেন, তখন `parse_dates=['column_name']` প্যারামিটারটি ব্যবহার করলে Pandas অটোমেটিকালি ওই কলামকে **Datetime**-এ রূপান্তর করে নেয়।

---

In [67]:
# Now we'll read another CSV file and convert it to a DataFrame.

std_com_data_df = pd.read_csv('student_completed_data.csv')
std_com_data_df

# The main reason for importing this file is, it contains some dates, which we can use to learn and exercise Datetime and Timedelta.

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

In [68]:
# Let's see the data types of the columns in the DataFrame.

std_com_data_df['EnrollmentDate']  # The output is: <class 'pandas.Series'>
# print(type(std_com_data_df['EnrollmentDate']))  # The output is: <class 'pandas.Series'>
# std_com_data_df['EnrollmentDate'].dtypes    # The output is: <StringDtype(na_value=nan)>
# std_com_data_df['EnrollmentDate'].dtype    # The output is: <StringDtype(na_value=nan)>

# So, this column has a string type of data. If we see the table, then hover the mouse pointer over the column header 'EnrollmentDate'; it'll pop up a modal, with some information, where you will see Data Type: str.

0     2024-09-01
1     2024-08-11
2     2024-05-08
3     2024-07-05
4     2024-02-01
5     2024-09-07
6     2024-06-07
7     2024-03-22
8     2024-02-12
9     2024-06-19
10    2024-03-14
11    2024-08-04
12    2024-06-07
13    2024-01-04
14    2024-02-22
15    2024-03-23
16    2024-01-18
17    2024-06-23
18    2024-04-19
19    2024-07-21
Name: EnrollmentDate, dtype: str

In [69]:
# Now we'll convert the 'EnrollmentDate' column to a Datetime column.

std_com_data_df['EnrollmentDate'] = pd.to_datetime(std_com_data_df['EnrollmentDate'])

In [70]:
# Now we'll see the dtype of the column 'EnrollmentDate'.

std_com_data_df['EnrollmentDate']

# So, this column has a datetime64[us] type of data. If we see the table, then hover the mouse pointer over the column header 'EnrollmentDate'; it'll pop up a modal, with some information, where you will see Data Type: datetime64[us].
# That means we have successfully changed the data type of each value of the column from string to datetime64[us].

0    2024-09-01
1    2024-08-11
2    2024-05-08
3    2024-07-05
4    2024-02-01
5    2024-09-07
6    2024-06-07
7    2024-03-22
8    2024-02-12
9    2024-06-19
10   2024-03-14
11   2024-08-04
12   2024-06-07
13   2024-01-04
14   2024-02-22
15   2024-03-23
16   2024-01-18
17   2024-06-23
18   2024-04-19
19   2024-07-21
Name: EnrollmentDate, dtype: datetime64[us]

In [71]:
# Now we want to see/add another column which will represent only the enrollment year.

std_com_data_df['EnrollmentDate'].dt.year
# std_com_data_df['Enrollment Year'] = std_com_data_df['EnrollmentDate'].dt.year

0     2024
1     2024
2     2024
3     2024
4     2024
5     2024
6     2024
7     2024
8     2024
9     2024
10    2024
11    2024
12    2024
13    2024
14    2024
15    2024
16    2024
17    2024
18    2024
19    2024
Name: EnrollmentDate, dtype: int32

In [72]:
# Now we want to see/add another column which will represent only the enrollment month.

std_com_data_df['EnrollmentDate'].dt.month
# std_com_data_df['Enrollment Month'] = std_com_data_df['EnrollmentDate'].dt.month

0     9
1     8
2     5
3     7
4     2
5     9
6     6
7     3
8     2
9     6
10    3
11    8
12    6
13    1
14    2
15    3
16    1
17    6
18    4
19    7
Name: EnrollmentDate, dtype: int32

In [73]:
# Now we want to see/add another column which will represent only the enrollment date.

std_com_data_df['EnrollmentDate'].dt.day
# std_com_data_df['Enrollment Day'] = std_com_data_df['EnrollmentDate'].dt.day

0      1
1     11
2      8
3      5
4      1
5      7
6      7
7     22
8     12
9     19
10    14
11     4
12     7
13     4
14    22
15    23
16    18
17    23
18    19
19    21
Name: EnrollmentDate, dtype: int32

In [74]:
# Now we'll convert the 'FinishedDate' column to a Datetime column.

std_com_data_df['FinishedDate'] = pd.to_datetime(std_com_data_df['FinishedDate'])
std_com_data_df

# Now, this FinishedDate column has a datetime64[us] type of data. If we see the table, then hover the mouse pointer over the column header 'FinishedDate'; it'll pop up a modal, with some information, where you will see Data Type: datetime64[us].
# That means we have successfully changed the data type of each value of the FinishedDate column from string to datetime64[us].

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

In [75]:
# Now we'll see how long did it take for students to finish the course. That means the duration in between EnrollmentDate to FinishedDate.

std_com_data_df['Total time to finish the course'] = std_com_data_df['FinishedDate'] - std_com_data_df['EnrollmentDate']
# std_com_data_df['FinishedDate'] - std_com_data_df['EnrollmentDate']

#### To learn more, visit https://pandas.pydata.org/pandas-docs/version/2.1.0/reference/api/pandas.to_datetime.html and https://www.programiz.com/python-programming/pandas/methods/to_datetime

# Groupby

In [76]:
std_com_data_df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Total time to finish the course
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,113 days
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,88 days
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,92 days
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,80 days
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,76 days
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,115 days
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,43 days
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,40 days
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,117 days
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,61 days
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,89 days
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,82 days
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,57 days
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,79 days
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,84 days
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,90 days
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,58 days
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,89 days
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,120 days
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,82 days

In [77]:
# Now we'll group the DataFrame by the 'Instructor' column. And will save it in a new variable.

std_com_grp_instr = std_com_data_df.groupby('Instructor')   # The output is: <pandas.api.typing.DataFrameGroupBy object at 0x000001B8A9B7D160>
std_com_grp_instr

In [78]:
# std_com_grp_instr.sum()

# As we currently have datetime64 type of data in EnrollmentDate and FinishedDate, we need to convert them back to str data type, or we need to drop these two columns.
std_com_data_df['EnrollmentDate'] = std_com_data_df['EnrollmentDate'].astype(str)
std_com_data_df['FinishedDate'] = std_com_data_df['FinishedDate'].astype(str)
std_com_data_df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Total time to finish the course
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,113 days
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,88 days
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,92 days
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,80 days
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,76 days
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,115 days
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,43 days
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,40 days
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,117 days
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,61 days
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,89 days
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,82 days
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,57 days
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,79 days
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,84 days
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,90 days
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,58 days
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,89 days
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,120 days
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,82 days

In [79]:
# Now we'll see the sum of the values in the DataFrame grouped by the 'Instructor' column.

std_com_grp_instr.sum()

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Location,Total Marks,Total time to finish the course
Instructor,,,,,,,,
Mr. David,PH0005PH0006PH0007PH0010PH0013PH0014PH0015PH00...,Kamal UddinLaila BegumMahmudul HasanPriya Shar...,CompletedCompletedCompletedCompletedCompletedC...,2024-02-012024-09-072024-06-072024-06-192024-0...,2024-04-172024-12-312024-07-202024-08-192024-0...,SylhetKhulnaChattogramDhakaDhakaSylhetRajshahi...,2399,662 days
Mr. Karim,PH0002PH0004PH0009PH0011PH0012PH0019PH0020,Fatima AkhterJannatul FerdousOmar FaruqRahim S...,CompletedCompletedCompletedCompletedCompletedC...,2024-08-112024-07-052024-02-122024-03-142024-0...,2024-11-072024-09-232024-06-082024-06-112024-1...,DhakaKhulnaDhakaSylhetSylhetSylhetKhulna,1911,658 days
Ms. Salma,PH0001PH0003PH0008PH0016,Alif RahmanImran HossainNadia IslamZiaur Rahman,CompletedCompletedCompletedCompleted,2024-09-012024-05-082024-03-222024-03-23,2024-12-232024-08-082024-05-012024-06-21,KhulnaDhakaKhulnaRajshahi,1049,335 days

In [80]:
# Now we'll see the sum of some selected values in the DataFrame grouped by the 'Instructor' column.


# Selecting only the 'Total Marks' and 'Total time to finish the course' columns and then summing them.
# std_com_grp_instr[['Total Marks', 'Total time to finish the course']].sum()


# Or summing the entire DataFrame first and then selecting only the 'Total Marks' and 'Total time to finish the course' columns.
std_com_grp_instr.sum()[['Total Marks', 'Total time to finish the course']]

            Total Marks Total time to finish the course
Instructor
Mr. David          2399                        662 days
Mr. Karim          1911                        658 days
Ms. Salma          1049                        335 days

In [81]:
# Now we'll see the maximum value in the DataFrame grouped by the 'Instructor' column.

std_com_grp_instr.max()[['Total Marks', 'Total time to finish the course']]

            Total Marks Total time to finish the course
Instructor
Mr. David           291                        115 days
Mr. Karim           291                        120 days
Ms. Salma           300                        113 days

In [82]:
# Now we'll see the minimum value in the DataFrame grouped by the 'Instructor' column.

std_com_grp_instr.min()[['Total Marks', 'Total time to finish the course']]

            Total Marks Total time to finish the course
Instructor
Mr. David           236                         43 days
Mr. Karim           253                         80 days
Ms. Salma           234                         40 days

In [83]:
# Now we'll see the average value in the DataFrame grouped by the 'Instructor' column.

std_com_grp_instr[['Total Marks', 'Total time to finish the course']].mean()

            Total Marks Total time to finish the course
Instructor
Mr. David    266.555556                73 days 13:20:00
Mr. Karim    273.000000                94 days 00:00:00
Ms. Salma    262.250000                83 days 18:00:00

In [84]:
# Now we'll see the first value in the DataFrame grouped by the 'Instructor' column.

std_com_grp_instr.first()[['Total Marks', 'Total time to finish the course']]

            Total Marks Total time to finish the course
Instructor
Mr. David           254                         76 days
Mr. Karim           271                         88 days
Ms. Salma           300                        113 days

In [85]:
# Now we'll see the last value in the DataFrame grouped by the 'Instructor' column.

std_com_grp_instr.last()[['Total Marks', 'Total time to finish the course']]

            Total Marks Total time to finish the course
Instructor
Mr. David           278                         89 days
Mr. Karim           253                         82 days
Ms. Salma           234                         90 days

# Solution of the LEETCODE problem: 196. Delete Duplicate Emails
Url: https://leetcode.com/problems/delete-duplicate-emails/description/

In [86]:
# We have a given list of emails.

# email_data = [
#     [1, 'john@example.com'],
#     [2, 'bob@example.com'],
#     [3, 'john@example.com']
# ]


email_data = [
    [1, 'abc@efg.com'],
    [1, 'abc@efg.com'],
]



print(email_data)
print(type(email_data))  # The output is: list

[[1, 'abc@efg.com'], [1, 'abc@efg.com']]
<class 'list'>

In [87]:
# Now we'll convert the list into a DataFrame. And I want to remove the index column.

person_df = pd.DataFrame(email_data, columns=['id', 'email']).astype({'id':'int64', 'email':'object'})
person_df

   id        email
0   1  abc@efg.com
1   1  abc@efg.com

In [88]:
def delete_duplicate_emails(person: pd.DataFrame) -> None:

    # First, I want to sort the rows according to the 'id' column.
    person.sort_values(by='id', ascending=True, inplace=True)

    # Then, I want to remove the duplicate emails and keep only the first occurrence of each email.
    person.drop_duplicates(subset=['email'], keep='first', inplace=True)

    # Now, I want to print the DataFrame.
    print(person)


delete_duplicate_emails(person_df)

   id        email
0   1  abc@efg.com

# Solution of the LEETCODE problem: 1907. Count Salary Categories
Url: https://leetcode.com/problems/count-salary-categories/description/

In [89]:
# We have a given list of account IDs and their corresponding incomes.

account_data = [
    [3, 108939],
    [2, 12747],
    [8, 87709],
    [6, 91796]
]

print(account_data)
print(type(account_data))

[[3, 108939], [2, 12747], [8, 87709], [6, 91796]]
<class 'list'>

In [90]:
# Now we'll convert the list into a DataFrame. And I want to remove the index column.

accounts_df = pd.DataFrame(account_data, columns=['account_id', 'income']).astype({'account_id': 'Int64', 'income': 'Int64'})
accounts_df

   account_id  income
0           3  108939
1           2   12747
2           8   87709
3           6   91796

In [91]:
def count_salary_categories(accounts: pd.DataFrame) -> pd.DataFrame:
    # First, I will count the income under each category.

    # high_salary_count = (accounts['income'] > 50000).sum()
    # average_salary_count = ((accounts['income'] >= 20000) & (accounts['income'] <= 50000)).sum()
    # low_salary_count = (accounts['income'] < 20000).sum()
    # OR
    high_salary_count = accounts['income'].gt(50000).sum()
    average_salary_count = accounts['income'].between(20000, 50000, inclusive="both").sum()
    low_salary_count = accounts['income'].lt(20000).sum()

    print(high_salary_count)
    print(average_salary_count)
    print(low_salary_count)

    # Now with these data, I will create a new DataFrame, with columns 'category' and 'accounts_count'.
    new_accounts_df = pd.DataFrame(
        {
            'category': [
                'Low Salary',
                'Average Salary',
                'High Salary'

            ],
            'accounts_count': [
                low_salary_count,
                average_salary_count,
                high_salary_count
            ]
        }
    )

    # Now will return the new DataFrame.
    return new_accounts_df


count_salary_categories(accounts_df)

3
0
1

         category  accounts_count
0      Low Salary               1
1  Average Salary               0
2     High Salary               3

# Solution of the CODECHEF problem: Filling Missing Data in Pandas
Url: https://www.codechef.com/learn/course/pandas/LPDP06/problems/LPDPR29

In [92]:
import pandas as pd
import numpy as np

# Here is the given DataFrame
df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, None, 10],
    'C': ['a', 'b', 'c', None, 'e']
})


# df
# df.dtypes
# print(type(df))
print(df)


# Replace null values based on given conditions
df_filled1 = df.fillna({'A': 0,'B': 99,'C': 'unknown',})
print(df_filled1)


# Forward fill column B
df_filled2 = df.copy()
df_filled2['B'] = df_filled2['B'].ffill()
print(df_filled2)


# Fills missing values in numeric columns with the mean of the column and in string columns with 'Unknown'.
df_filled3 = df.copy()

for column in df_filled3.columns:
    if df_filled3[column].dtype == 'float64':
        df_filled3[column] = df_filled3[column].fillna(df_filled3[column].mean())
    else:
        df_filled3[column] = df_filled3[column].fillna('Unknown')

print(df_filled3)

     A     B    C
0  1.0   5.0    a
1  2.0   NaN    b
2  NaN   NaN    c
3  4.0   NaN  NaN
4  5.0  10.0    e
     A     B        C
0  1.0   5.0        a
1  2.0  99.0        b
2  0.0  99.0        c
3  4.0  99.0  unknown
4  5.0  10.0        e
     A     B    C
0  1.0   5.0    a
1  2.0   5.0    b
2  NaN   5.0    c
3  4.0   5.0  NaN
4  5.0  10.0    e
     A     B        C
0  1.0   5.0        a
1  2.0   7.5        b
2  3.0   7.5        c
3  4.0   7.5  Unknown
4  5.0  10.0        e

# Solution of the CODECHEF problem: Dropping missing data
Url: https://www.codechef.com/learn/course/pandas/LPDP06/problems/LPDPR28

In [93]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, None, 10],
    'C': ['a', 'b', 'c', None, 'e']
})


print(df)


# Drop rows where column A has missing values
df_dropped1 = df.copy()
df_dropped1.dropna(subset=['A'], inplace=True)
print(df_dropped1)


# Drop rows with less than 2 non-null values
df_dropped2 = df.copy()
df_dropped2.dropna(thresh=2, inplace=True)
print(df_dropped2)


# Drop rows where both Column A and Column B has missing values
df_dropped3 = df.copy()
df_dropped3.dropna(subset=['A', 'B'], how="all", inplace=True)
print(df_dropped3)

     A     B    C
0  1.0   5.0    a
1  2.0   NaN    b
2  NaN   NaN    c
3  4.0   NaN  NaN
4  5.0  10.0    e
     A     B    C
0  1.0   5.0    a
1  2.0   NaN    b
3  4.0   NaN  NaN
4  5.0  10.0    e
     A     B  C
0  1.0   5.0  a
1  2.0   NaN  b
4  5.0  10.0  e
     A     B    C
0  1.0   5.0    a
1  2.0   NaN    b
3  4.0   NaN  NaN
4  5.0  10.0    e

# Solution of the CODECHEF problem: GroupBy Operation
Url: https://www.codechef.com/learn/course/pandas/LPD10/problems/LPDPR46

In [94]:
import pandas as pd
import numpy as np

# Create a sample DataFrame
df = pd.DataFrame({
    'Category': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Value1': [10, 20, 30, 40, 50, 60],
    'Value2': [100, 200, 300, 400, 500, 600]
})

print(df)

  Category  Value1  Value2
0        A      10     100
1        B      20     200
2        A      30     300
3        B      40     400
4        A      50     500
5        B      60     600

In [95]:
# Basic groupby and aggregation
print("Mean of Value1 for each Category:")
print(df.groupby('Category')['Value1'].mean())

Mean of Value1 for each Category:
Category
A    30.0
B    40.0
Name: Value1, dtype: float64

In [96]:
print("Max of Value2 for each Category:")
print(df.groupby('Category')['Value1'].max())

Max of Value2 for each Category:
Category
A    50
B    60
Name: Value1, dtype: int64

In [97]:
print("Sum of Value1 for each Category:")
print(df.groupby('Category')['Value1'].sum())

Sum of Value1 for each Category:
Category
A     90
B    120
Name: Value1, dtype: int64

---