# Email address: kamal.md.zahid@gmail.com

### 0) Starter Code (Run First)

In [1]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
    "id": ids,
    "age": ages,
    "salary": salaries,
    "dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")

Sample Data Created and Saved as employees.csv

## 1) NumPy — 5 Questions

### Answer to the Question 1:

In [2]:
DF

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [3]:
# Creating NumPy array from the ages data generated above.
ages_array = np.array(ages)


print(f"Original ages data: {ages_array}")
print(f"Type of the ages array: {type(ages_array)}")
print(f"Data type of the ages array: {ages_array.dtype}")
print(f"Dimensions of the ages array: {ages_array.ndim}")
print(f"Shape of the ages array: {ages_array.shape}")
print(f"Size of the ages array: {ages_array.size}")

Original ages data: [56 46 32 25 38 56 36 40 28 28]
Type of the ages array: <class 'numpy.ndarray'>
Data type of the ages array: int32
Dimensions of the ages array: 1
Shape of the ages array: (10,)
Size of the ages array: 10

### Answer to the Question 2:

In [4]:
# Creating NumPy array from the salaries data generated above.
salaries_array = np.array(salaries)


# Calculating the highest, lowest, and average salaries
highest_salary = np.max(salaries_array)
lowest_salary = np.min(salaries_array)
average_salary = np.mean(salaries_array)


print(f"Original salaries data: {salaries_array}")
print(f"Highest Salary: {highest_salary}")
print(f"Lowest Salary: {lowest_salary}")
print(f"Average/Mean Salary: {average_salary}")


print(f"Original ages data: {ages_array}")
print(f"Average/Mean Age: {ages_array.mean()}")

Original salaries data: [77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
Highest Salary: 89735
Lowest Salary: 30769
Average/Mean Salary: 57446.9
Original ages data: [56 46 32 25 38 56 36 40 28 28]
Average/Mean Age: 38.5

### Answer to the Question 3:

In [5]:
# Finding all ages greater than 30, using the boolean condition
ages_array_greater_than_30 = ages_array[ages_array > 30]
print(f"All ages greater than 30: {ages_array_greater_than_30}")


# Now printing the count of employees with age older than 30
print(f"Count of employees with age older than 30: {len(ages_array_greater_than_30)}")


#-------------------- OR --------------------


# Finding all ages greater than 30, using the boolean condition
ages_array_greater_than_30 = np.where(ages_array > 30, ages_array, None)
print(f"All ages greater than 30: {ages_array_greater_than_30}")


# Now printing the count of employees with age older than 30
print(f"Count of employees with age older than 30: {np.count_nonzero(ages_array_greater_than_30)}")

All ages greater than 30: [56 46 32 38 56 36 40]
Count of employees with age older than 30: 7
All ages greater than 30: [56 46 32 None 38 56 36 40 None None]
Count of employees with age older than 30: 7

### Answer to the Question 4:

In [6]:
# Creating a new array with all employee ages increased by 5 years
# increased_ages_array = ages_array + 5
increased_ages_array = np.add(ages_array, 5)


# Now printing the new ages array
print(f"New increased ages array: {increased_ages_array}")

New increased ages array: [61 51 37 30 43 61 41 45 33 33]

### Answer to the Question 5:

In [7]:
# Calculating the total salary expenses of all employees
total_salary_expenses = np.sum(salaries_array)
print(f"Total salary expenses: {total_salary_expenses}")


# Calculating the difference between Maximum and Minimum salary
salary_difference = np.subtract(highest_salary, lowest_salary)
print(f"Difference between Maximum and Minimum salary: {salary_difference}")

Total salary expenses: 574469
Difference between Maximum and Minimum salary: 58966

## 2) Pandas — 5 Questions

### Answer to the Question 6:

In [8]:
# Loading the employees.csv file
employees_df = pd.read_csv("employees.csv")


# Displaying the first 5 rows of the DataFrame
employees_df.head(5)

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR

In [9]:
# Printing basic information about the DataFrame
print(f"Basic information about the DataFrame: ")
employees_df.info()

Basic information about the DataFrame:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     int64
 1   age     10 non-null     int64
 2   salary  10 non-null     int64
 3   dept    10 non-null     str
dtypes: int64(3), str(1)
memory usage: 488.0 bytes

In [10]:
# Printing summary statistics of the DataFrame
print(f"Summary statistics of the DataFrame: ")
employees_df.describe()

Summary statistics of the DataFrame:

             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000

### Answer to the Question 7:

In [11]:
# Displaying only the id, age, and salary columns of the DataFrame and only the last 3 rows
employees_df[['id', 'age', 'salary']].tail(3)

   id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311

### Answer to the Question 8:

In [12]:
# Finding the employees who work only in the IT department
# employees_df_it_dpt = employees_df[employees_df['dept'] == 'IT']
# employees_df_it_dpt = employees_df.loc[employees_df['dept'] == 'IT']
# employees_df_it_dpt = employees_df.iloc[employees_df['dept'] == 'IT']
employees_df_it_dpt = employees_df.query("dept == 'IT'")
employees_df_it_dpt

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT

In [13]:
# Now finding the total number of employees in the IT department
print(f"Total number of employees in the IT department: {len(employees_df_it_dpt)}")

Total number of employees in the IT department: 3

### Answer to the Question 9:

In [14]:
# Sorting the DataFrame by Salary, in descending order and displaying the top 3 highest paid employees along with their department and age
employees_df[['age', 'salary', 'dept']].sort_values(by='salary', ascending=False).head(3)

   age  salary     dept
6   36   89735  Finance
7   40   86101       IT
0   56   77191       HR

### Answer to the Question 10:

In [15]:
# Replacing all salary values with 80000, where the salary value is greater than 80000
employees_df.loc[employees_df['salary'] > 80000, 'salary'] = 80000
employees_df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   80000  Finance
7   8   40   80000       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [16]:
# Now finding the new average salary of all employees of the DataFrame
average_salary_new = employees_df['salary'].mean()
print(f"New average salary of all employees: {average_salary_new}")

New average salary of all employees: 55863.3

---