# Practice Problem Solution 01

In [1]:
import numpy as np
import pandas as pd

# Creating a list
list01 = list([10, 20, 30, 40, 50])
list01
# type(list01)        # Output: list

[10, 20, 30, 40, 50]

In [2]:
# Converting the list into a Pandas Series
series01 = pd.Series(list01)
series01
# type(series01)      # Output: pandas.Series

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
# Creating a DataFrame with columns 'Name', 'Age' and 'City', containing at least 4 rows of data.

df_persons = pd.DataFrame(
    {
        'Name': ['Hadee', 'Shamim', 'Nahid', 'Sumon'],
        'Age': [25, 27, 28, 29],
        'City': ['Chittagong', 'Khulna', 'Bikrompur', 'Netrokona']
    }
)

df_persons
# type(df_persons)        # Output: pandas.DataFrame

     Name  Age        City
0   Hadee   25  Chittagong
1  Shamim   27      Khulna
2   Nahid   28   Bikrompur
3   Sumon   29   Netrokona

# Practice Problem Solution 02

In [4]:
# The number of rows

# len(df_persons)
df_persons.shape[0]

4

In [5]:
# The number of columns

df_persons.shape[1]

3

In [6]:
# Finding the data type of the column

df_persons.dtypes

Name      str
Age     int64
City      str
dtype: object

In [7]:
# Finding the summary statistics of the DataFrame

df_persons.describe()

             Age
count   4.000000
mean   27.250000
std     1.707825
min    25.000000
25%    26.500000
50%    27.500000
75%    28.250000
max    29.000000

# Practice Problem Solution 03

In [8]:
# Creating a dictionary from the given data
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}

# data


# Now creating the DataFrame from the above dictionary

data_df = pd.DataFrame(data)
data_df

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [9]:
# Getting all the columns of the DataFrame
# data_df.columns


# Creating a NumPy array from the columns and printing it like an array
data_df_columns = np.array(data_df.columns)
print(data_df_columns)

['Product' 'Price' 'Quantity']

In [10]:
# Finding the indexes of the DataFrame

data_df.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
# Accessing a single column of the DataFrame

data_df['Product']

0       Pen
1      Book
2    Eraser
3    Pencil
Name: Product, dtype: str

In [12]:
# Accessing a full row on the DataFrame

data_df.loc[1]

Product     Book
Price         50
Quantity      60
Name: 1, dtype: object

# Practice Problem Solution 04

In [13]:
# Using .loc function, showing the first row

data_df.loc[0]

Product     Pen
Price        10
Quantity    100
Name: 0, dtype: object

In [14]:
# Using .loc function, showing the second column

data_df.loc[:, 'Price']

0    10
1    50
2     5
3     7
Name: Price, dtype: int64

In [15]:
# Using .loc function, showing a 2x2 block of data from the middle of the DataFrame

data_df.loc[1:2, ['Product', 'Price']]
# data_df.loc[1:2, ['Product', 'Price']].shape

  Product  Price
1    Book     50
2  Eraser      5

In [16]:
# Using .iloc function, showing the first row

data_df.iloc[0]

Product     Pen
Price        10
Quantity    100
Name: 0, dtype: object

In [17]:
# Using .iloc function, showing the second column

data_df.iloc[:, 1]

0    10
1    50
2     5
3     7
Name: Price, dtype: int64

In [18]:
# Using .iloc function, showing a 2x2 block of data from the middle of the DataFrame

data_df.iloc[1:3, [0, 1]]

  Product  Price
1    Book     50
2  Eraser      5

# Practice Problem Solution 05

In [19]:
# Creating a python dictionary of student names and marks with 4x3 dimension.

students_data = {
    'Student Name': ['Arif', 'Sajid', 'Nabila', 'Riya'],
    'Math Marks': [85, 92, 78, 88],
    'Science Marks': [90, 85, 82, 94],
    'English Marks': [75, 80, 90, 78]
}

# students_data


# Now creating the DataFrame from the above dictionary

students_df = pd.DataFrame(students_data)
students_df

  Student Name  Math Marks  Science Marks  English Marks
0         Arif          85             90             75
1        Sajid          92             85             80
2       Nabila          78             82             90
3         Riya          88             94             78

In [20]:
# Now will drop the last column using .drop() function

students_df.drop('English Marks', axis=1, inplace=True)
students_df

  Student Name  Math Marks  Science Marks
0         Arif          85             90
1        Sajid          92             85
2       Nabila          78             82
3         Riya          88             94

In [21]:
# Now will drop the first row using index

students_df.drop(index=0, inplace=True)
students_df

  Student Name  Math Marks  Science Marks
1        Sajid          92             85
2       Nabila          78             82
3         Riya          88             94

# Practice Problem Solution 06

In [22]:
# Creating a python dictionary of employee names, departments and salary.

employees_data = {
    'Name': ['Rahim', 'Karim', 'Salma', 'Jashim', 'Tania', 'Arif', 'Lata', 'Sohan', 'Mitu', 'Sajid'],
    'Department': ['IT', 'HR', 'Finance', 'IT', 'Marketing', 'Admin', 'Finance', 'IT', 'Marketing', 'HR'],
    'Salary': [65000, 45000, 55000, 70000, 48000, 42000, 58000, 72000, 47000, 46000]
}

# employees_data


# Now creating the DataFrame from the above dictionary

employees_df = pd.DataFrame(employees_data)
employees_df

     Name Department  Salary
0   Rahim         IT   65000
1   Karim         HR   45000
2   Salma    Finance   55000
3  Jashim         IT   70000
4   Tania  Marketing   48000
5    Arif      Admin   42000
6    Lata    Finance   58000
7   Sohan         IT   72000
8    Mitu  Marketing   47000
9   Sajid         HR   46000

In [26]:
# Sorting the DataFrame, according to the Salary in ascending order and according to the Name in descending order

employees_df.sort_values(by=['Salary', 'Name'], ascending=[True, False])

     Name Department  Salary
5    Arif      Admin   42000
1   Karim         HR   45000
9   Sajid         HR   46000
8    Mitu  Marketing   47000
4   Tania  Marketing   48000
2   Salma    Finance   55000
6    Lata    Finance   58000
0   Rahim         IT   65000
3  Jashim         IT   70000
7   Sohan         IT   72000

# Practice Problem Solution 07

In [35]:
# Creating a python dictionary of students' names and score.

students_data = {
    'Name': ['Sabbir', 'Anika', 'Tanvir', 'Mitu', 'Fahad', 'Jannat', 'Rakib', 'Nodi'],
    'Score': [85, 92, 38, 95, 88, 30, 32, 91]
}

# students_data


# Now creating the DataFrame from the above dictionary

students_df = pd.DataFrame(students_data)
students_df

     Name  Score
0  Sabbir     85
1   Anika     92
2  Tanvir     38
3    Mitu     95
4   Fahad     88
5  Jannat     30
6   Rakib     32
7    Nodi     91

In [36]:
# Now filtering students with Score > 60.

students_df.loc[students_df['Score'] > 60]

     Name  Score
0  Sabbir     85
1   Anika     92
3    Mitu     95
4   Fahad     88
7    Nodi     91

In [37]:
# Now filtering students with Score < 40.

students_df.loc[students_df['Score'] < 40]

     Name  Score
2  Tanvir     38
5  Jannat     30
6   Rakib     32

---